dist: trusty
language: php

notifications:
  email: false

cache:
  directories:
    - ~/.composer/cache/files
    - vendor

jobs:
  include:
    - php: 7.2
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.3

before_install:
  - phpenv config-rm xdebug.ini

install:
  - composer update ${COMPOSER_FLAGS} --prefer-dist --no-interaction

script:
  - make run-composer-validate
  - make run-phpstan
  - make run-phpunit
  - make run-php-cs-fixer@travis
